// /constants/program-registrants.ts

export type ProgramType = "online" | "offline";

export interface ProgramRegistration {
  id: string;
  childName: string;
  parentName: string;
  programName: string;
  programType: ProgramType;
  date: string; // ISO date string, contoh: "2024-06-15"
  source: string; // contoh: "Landing Page", "WhatsApp"
}

export const dummyProgramRegistrations: ProgramRegistration[] = [
  {
    id: "R001",
    childName: "Aisyah Putri",
    parentName: "Dewi Kartika",
    programName: "Kelas TK A Offline",
    programType: "offline",
    date: "2024-06-20",
    source: "Landing Page",
  },
  {
    id: "R002",
    childName: "Budi Pratama",
    parentName: "Rudi Pratama",
    programName: "Kelas TK B Offline",
    programType: "offline",
    date: "2024-06-20",
    source: "WhatsApp",
  },
  {
    id: "R003",
    childName: "Citra Lestari",
    parentName: "Lestari W.",
    programName: "Bimbel Online Dasar",
    programType: "online",
    date: "2024-06-20",
    source: "Instagram Ads",
  },
  {
    id: "R004",
    childName: "Dimas Arya",
    parentName: "Andi Arya",
    programName: "Bimbel Online Dasar",
    programType: "online",
    date: "2024-06-21",
    source: "Landing Page",
  },
  {
    id: "R005",
    childName: "Eka Saputra",
    parentName: "Sari Saputra",
    programName: "Kelas TK A Offline",
    programType: "offline",
    date: "2024-06-21",
    source: "Referal Teman",
  },
  {
    id: "R006",
    childName: "Farah Nabila",
    parentName: "Imam N.",
    programName: "Kelas TK B Offline",
    programType: "offline",
    date: "2024-06-22",
    source: "WhatsApp",
  },
  {
    id: "R007",
    childName: "Gilang Ramadhan",
    parentName: "Rina Ramadhan",
    programName: "Bimbel Online Dasar",
    programType: "online",
    date: "2024-06-22",
    source: "Instagram Ads",
  },
  {
    id: "R008",
    childName: "Hana Zahra",
    parentName: "Ali Fahmi",
    programName: "Kelas TK A Offline",
    programType: "offline",
    date: "2024-06-23",
    source: "Landing Page",
  },
  {
    id: "R009",
    childName: "Iqbal Fajar",
    parentName: "Fajar S.",
    programName: "Bimbel Online Dasar",
    programType: "online",
    date: "2024-06-23",
    source: "WhatsApp",
  },
  {
    id: "R010",
    childName: "Jihan Naila",
    parentName: "Naila P.",
    programName: "Kelas TK B Offline",
    programType: "offline",
    date: "2024-06-24",
    source: "Landing Page",
  },
  {
    id: "R101",
    childName: "Anak 1",
    parentName: "Orangtua 1",
    programName: "Kelas TK A Offline",
    programType: "offline",
    date: "2024-03-05",
    source: "Instagram Ads",
  },
  {
    id: "R102",
    childName: "Anak 2",
    parentName: "Orangtua 2",
    programName: "Bimbel Online Dasar",
    programType: "online",
    date: "2024-03-11",
    source: "Instagram Ads",
  },
  {
    id: "R103",
    childName: "Anak 3",
    parentName: "Orangtua 3",
    programName: "Kelas TK A Offline",
    programType: "offline",
    date: "2024-03-18",
    source: "Instagram Ads",
  },
  {
    id: "R104",
    childName: "Anak 4",
    parentName: "Orangtua 4",
    programName: "Bimbel Online Dasar",
    programType: "online",
    date: "2024-03-24",
    source: "Instagram Ads",
  },
  {
    id: "R105",
    childName: "Anak 5",
    parentName: "Orangtua 5",
    programName: "Kelas TK A Offline",
    programType: "offline",
    date: "2024-03-07",
    source: "Instagram Ads",
  },
  {
    id: "R106",
    childName: "Anak 6",
    parentName: "Orangtua 6",
    programName: "Bimbel Online Dasar",
    programType: "online",
    date: "2024-03-16",
    source: "Instagram Ads",
  },
  {
    id: "R107",
    childName: "Anak 7",
    parentName: "Orangtua 7",
    programName: "Kelas TK A Offline",
    programType: "offline",
    date: "2024-03-22",
    source: "Instagram Ads",
  },
  {
    id: "R108",
    childName: "Anak 8",
    parentName: "Orangtua 8",
    programName: "Bimbel Online Dasar",
    programType: "online",
    date: "2024-03-28",
    source: "Instagram Ads",
  },
  {
    id: "R109",
    childName: "Anak 9",
    parentName: "Orangtua 9",
    programName: "Kelas TK A Offline",
    programType: "offline",
    date: "2024-03-14",
    source: "Instagram Ads",
  },
  {
    id: "R110",
    childName: "Anak 10",
    parentName: "Orangtua 10",
    programName: "Bimbel Online Dasar",
    programType: "online",
    date: "2024-03-27",
    source: "Instagram Ads",
  },

  // ===================== APRIL 2024 =====================

  {
    id: "R111",
    childName: "Siswa 1",
    parentName: "Wali 1",
    programName: "Calistung Offline",
    programType: "offline",
    date: "2024-04-03",
    source: "Landing Page",
  },
  {
    id: "R112",
    childName: "Siswa 2",
    parentName: "Wali 2",
    programName: "English Kids Online",
    programType: "online",
    date: "2024-04-07",
    source: "Landing Page",
  },
  {
    id: "R113",
    childName: "Siswa 3",
    parentName: "Wali 3",
    programName: "Calistung Offline",
    programType: "offline",
    date: "2024-04-12",
    source: "Landing Page",
  },
  {
    id: "R114",
    childName: "Siswa 4",
    parentName: "Wali 4",
    programName: "English Kids Online",
    programType: "online",
    date: "2024-04-15",
    source: "Landing Page",
  },
  {
    id: "R115",
    childName: "Siswa 5",
    parentName: "Wali 5",
    programName: "Calistung Offline",
    programType: "offline",
    date: "2024-04-18",
    source: "Landing Page",
  },
  {
    id: "R116",
    childName: "Siswa 6",
    parentName: "Wali 6",
    programName: "English Kids Online",
    programType: "online",
    date: "2024-04-20",
    source: "Landing Page",
  },
  {
    id: "R117",
    childName: "Siswa 7",
    parentName: "Wali 7",
    programName: "Calistung Offline",
    programType: "offline",
    date: "2024-04-23",
    source: "Landing Page",
  },
  {
    id: "R118",
    childName: "Siswa 8",
    parentName: "Wali 8",
    programName: "English Kids Online",
    programType: "online",
    date: "2024-04-26",
    source: "Landing Page",
  },
  {
    id: "R119",
    childName: "Siswa 9",
    parentName: "Wali 9",
    programName: "Calistung Offline",
    programType: "offline",
    date: "2024-04-29",
    source: "Landing Page",
  },
  {
    id: "R120",
    childName: "Siswa 10",
    parentName: "Wali 10",
    programName: "English Kids Online",
    programType: "online",
    date: "2024-04-30",
    source: "Landing Page",
  },

  // ===================== MEI 2024 =====================

  {
    id: "R121",
    childName: "Kids 1",
    parentName: "Parent 1",
    programName: "Kelas TK B Offline",
    programType: "offline",
    date: "2024-05-02",
    source: "WhatsApp",
  },
  {
    id: "R122",
    childName: "Kids 2",
    parentName: "Parent 2",
    programName: "Bimbel Online Tahfidz",
    programType: "online",
    date: "2024-05-05",
    source: "WhatsApp",
  },
  {
    id: "R123",
    childName: "Kids 3",
    parentName: "Parent 3",
    programName: "Kelas TK B Offline",
    programType: "offline",
    date: "2024-05-09",
    source: "WhatsApp",
  },
  {
    id: "R124",
    childName: "Kids 4",
    parentName: "Parent 4",
    programName: "Bimbel Online Tahfidz",
    programType: "online",
    date: "2024-05-13",
    source: "WhatsApp",
  },
  {
    id: "R125",
    childName: "Kids 5",
    parentName: "Parent 5",
    programName: "Kelas TK B Offline",
    programType: "offline",
    date: "2024-05-15",
    source: "WhatsApp",
  },
  {
    id: "R126",
    childName: "Kids 6",
    parentName: "Parent 6",
    programName: "Bimbel Online Tahfidz",
    programType: "online",
    date: "2024-05-17",
    source: "WhatsApp",
  },
  {
    id: "R127",
    childName: "Kids 7",
    parentName: "Parent 7",
    programName: "Kelas TK B Offline",
    programType: "offline",
    date: "2024-05-21",
    source: "WhatsApp",
  },
  {
    id: "R128",
    childName: "Kids 8",
    parentName: "Parent 8",
    programName: "Bimbel Online Tahfidz",
    programType: "online",
    date: "2024-05-25",
    source: "WhatsApp",
  },
  {
    id: "R129",
    childName: "Kids 9",
    parentName: "Parent 9",
    programName: "Kelas TK B Offline",
    programType: "offline",
    date: "2024-05-27",
    source: "WhatsApp",
  },
  {
    id: "R130",
    childName: "Kids 10",
    parentName: "Parent 10",
    programName: "Bimbel Online Tahfidz",
    programType: "online",
    date: "2024-05-30",
    source: "WhatsApp",
  },
];
